[tool.poetry]
name = "btrfs-recon"
version = "0.1.0"
description = ""
authors = ["Zach Kanzler <they4kman@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
construct = "^2.10.67"
intervaltree = "^3.1.0"

[tool.poetry.dev-dependencies]
construct-typing = "^0.5.2"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
