"""Add unique/check constraints for Address

Revision ID: 275168ff8072
Revises: 
Create Date: 2022-01-21 02:52:13.945500-05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275168ff8072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('address_uniq_struct_ref', 'address', ['struct_type', 'struct_id'])
    op.create_check_constraint(
        'address_enforce_struct_ref_completeness',
        'address',
        '(struct_type IS NULL AND struct_id IS NULL) '
        'OR (struct_type IS NOT NULL AND struct_id IS NOT NULL)',
    )
    op.create_unique_constraint(None, 'filesystem', ['label'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filesystem', type_='unique')
    op.drop_constraint('address_uniq_struct_ref', 'address_enforce_struct_ref_completeness', type_='check')
    op.drop_constraint('address_uniq_struct_ref', 'address', type_='unique')
    # ### end Alembic commands ###
