"""Add KeyType(0) to enum type

Revision ID: 30a945ec1fef
Revises: ddd6be5957a2
Create Date: 2022-03-14 12:54:48.245893-04:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a945ec1fef'
down_revision = 'ddd6be5957a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute('''
            ALTER TYPE keytype ADD VALUE 'UNKNOWN';
        ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TYPE keytype RENAME to keytype_old;')
    op.execute('''
        create type keytype as enum ('InodeItem', 'InodeRef', 'InodeExtref', 'InodeXattr', 'OrphanItem', 'DirLogItem', 'DirLogIndex', 'DirItem', 'DirIndex', 'ExtentData', 'ExtentCsum', 'RootItem', 'RootBackref', 'RootRef', 'ExtentItem', 'MetadataItem', 'TreeBlockRef', 'ExtentDataRef', 'ExtentRefV0', 'SharedBlockRef', 'SharedDataRef', 'BlockGroupItem', 'FreeSpaceInfo', 'FreeSpaceExtent', 'FreeSpaceBitmap', 'DevExtent', 'DevItem', 'ChunkItem', 'QgroupStatus', 'QgroupInfo', 'QgroupLimit', 'QgroupRelation', 'TemporaryItem', 'PersistentItem', 'DevReplace');
    ''')
    op.execute('ALTER TABLE key ALTER COLUMN ty TYPE keytype USING ty::text::keytype;')
    op.execute('DROP TYPE keytype_old;')
    # ### end Alembic commands ###
