"""Add Subvol KeyTypes to enum type

Revision ID: a7ab0413b781
Revises: 30a945ec1fef
Create Date: 2022-03-15 14:05:20.812562-04:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ab0413b781'
down_revision = '30a945ec1fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute('''
            ALTER TYPE keytype ADD VALUE 'Subvol';
            ALTER TYPE keytype ADD VALUE 'ReceivedSubvol';
        ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TYPE keytype RENAME to keytype_old;')
    op.execute('''
        create type keytype as enum ('UNKNOWN', 'InodeItem', 'InodeRef', 'InodeExtref', 'InodeXattr', 'OrphanItem', 'DirLogItem', 'DirLogIndex', 'DirItem', 'DirIndex', 'ExtentData', 'ExtentCsum', 'RootItem', 'RootBackref', 'RootRef', 'ExtentItem', 'MetadataItem', 'TreeBlockRef', 'ExtentDataRef', 'ExtentRefV0', 'SharedBlockRef', 'SharedDataRef', 'BlockGroupItem', 'FreeSpaceInfo', 'FreeSpaceExtent', 'FreeSpaceBitmap', 'DevExtent', 'DevItem', 'ChunkItem', 'QgroupStatus', 'QgroupInfo', 'QgroupLimit', 'QgroupRelation', 'TemporaryItem', 'PersistentItem', 'DevReplace');
    ''')
    op.execute('ALTER TABLE key ALTER COLUMN ty TYPE keytype USING ty::text::keytype;')
    op.execute('DROP TYPE keytype_old;')
    # ### end Alembic commands ###
