"""Remove overly-strict FileExtentItem CHECK constraints

Revision ID: f380aa51b36a
Revises: eece6c9f11c6
Create Date: 2022-03-14 05:11:04.201707-04:00

"""
from alembic import op
import sqlalchemy as sa

from btrfs_recon.structure import ExtentDataType


# revision identifiers, used by Alembic.
revision = 'f380aa51b36a'
down_revision = 'eece6c9f11c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_extent_item_data_ref', 'file_extent_item', 'check')
    op.drop_constraint('file_extent_item_inline_data', 'file_extent_item', 'check')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'file_extent_item_inline_data',
        'file_extent_item',
        #language=postgresql
        '''
        type = 'INLINE'
            AND data IS NOT NULL
            AND disk_bytenr IS NULL
            AND disk_num_bytes IS NULL
            AND "offset" IS NULL
            AND num_bytes IS NULL
        ''',
    )
    op.create_check_constraint(
        'file_extent_item_data_ref',
        'file_extent_item',
        #language=postgresql
        '''
        type <> 'INLINE'
            AND data IS NULL
            AND disk_bytenr IS NOT NULL
            AND disk_num_bytes IS NOT NULL
            AND "offset" IS NOT NULL
            AND num_bytes IS NOT NULL
        ''',
    )
    # ### end Alembic commands ###
